import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import QRCode from "react-qr-code";
import io from "socket.io-client";
import { useState, useEffect, useRef } from "react";
import { Typography } from '@mui/material';

let socket;

export default function Home() {
  const [message, setMessage] = useState(null);
  const socketOpened = useRef(false);

  const socketInitializer = async () => {
    // We just call it because we don't need anything else out of it
    await fetch("/api/socket");
    console.log("HI")
    socket = io(process.env.BASE_URL, {
      path: "/api/socket",
    });

    socket.on("newIncomingMessage", (msg) => {
      console.log("hi")
      setMessage((msg)); //hi
    });

    socket.on('connect', () => {
        console.log('connected')
      })

    socket.on("connect_error", (err) => {
      console.log(`connect_error due to ${err.message}`);
      socket.connect();
    });
  };

  useEffect(() => {
    if(!socketOpened.current) {
      socketOpened.current = true;
      socketInitializer();
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="h1">Not Funny Tony</Typography>
        <QRCode value="https://htn-2022.vercel.app/signup"></QRCode>
        {
          message && <Typography variant="h4">{`Hi, ${message.name.toUpperCase()}!`}</Typography>
        }
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
